### PR TITLE
44 use fragment to pull in the head element for every page

### PR DESCRIPTION
**Pull request by Radsv**
I've added the header element for every page.

### CODE REVIEW

**Review by kavithamsc — APPROVED** [review]

**Review by kgraciano — APPROVED** [review]

**Comment by Blushu** [comment]
Hi, slight misunderstanding here. This issue ([#44](https://github.com/KC-LCW-Jan-23-Classroom/liftoff-south/issues/44)) was to bring in the <head> element from fragments onto every page:

`<head th:replace="fragments :: head">`

You've done the work for this issue ([#43](https://github.com/KC-LCW-Jan-23-Classroom/liftoff-south/issues/43)) which is for bringing in the navigation bar.

**Review by Blushu — CHANGES_REQUESTED** [review]
This PR should be bringing in the <head> element, not the <header>.

**Comment by Radsv** [comment]
> This PR should be bringing in the `<head>` element, not the `<header>`.

I edited the code to reflect the issue. Can you look at it and confirm if it is correct? Thank you

**Review by Blushu — APPROVED** [review]
Yes, you are adding the correct element now.

**Pull request merged**
